<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>preview</LangVersion>
    <RootNamespace>Tirax.SshManager</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Ssh.fs" />
    <Compile Include="AppEnvironment.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\libs\RZ.FSharp.Extension\src\RZ.FSharp.Extension\RZ.FSharp.Extension.fsproj" />
  </ItemGroup>

</Project>
